---
- name: installing services
  hosts: all
  become: true

  tasks:
  - name: Package installation
    dnf:
      name:
        - sysstat
        - httpd
      state: latest

  - name: Start apache service
    service:
      name: httpd
      state: started
