---
- name: Install Nginx service on remote servers
  hosts: all
  become: true

  tasks:
  - name: Install nginx
    dnf:
      name: nginx
      state: present

  - name: start nginx
    service:
      name: nginx
      state: started
